// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbV8QEJMQVTI1_sQSPEoo3BfKPNIQMV5Y',
    appId: '1:1070132034032:web:cdf8c9368da4989f1b4535',
    messagingSenderId: '1070132034032',
    projectId: 'studyflow-64b99',
    authDomain: 'studyflow-64b99.firebaseapp.com',
    storageBucket: 'studyflow-64b99.firebasestorage.app',
    measurementId: 'G-PSEQN10LSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqzVRpSCurk_JhVs8NTaaFMlGrwrog2l0',
    appId: '1:1070132034032:android:def2af0f59c290231b4535',
    messagingSenderId: '1070132034032',
    projectId: 'studyflow-64b99',
    storageBucket: 'studyflow-64b99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvs7wIxJlg_s_a9DkuTYdnuDjFC_iWanM',
    appId: '1:1070132034032:ios:d6a935be3757aac31b4535',
    messagingSenderId: '1070132034032',
    projectId: 'studyflow-64b99',
    storageBucket: 'studyflow-64b99.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvs7wIxJlg_s_a9DkuTYdnuDjFC_iWanM',
    appId: '1:1070132034032:ios:d6a935be3757aac31b4535',
    messagingSenderId: '1070132034032',
    projectId: 'studyflow-64b99',
    storageBucket: 'studyflow-64b99.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbV8QEJMQVTI1_sQSPEoo3BfKPNIQMV5Y',
    appId: '1:1070132034032:web:ff5bd8c34729ba6f1b4535',
    messagingSenderId: '1070132034032',
    projectId: 'studyflow-64b99',
    authDomain: 'studyflow-64b99.firebaseapp.com',
    storageBucket: 'studyflow-64b99.firebasestorage.app',
    measurementId: 'G-R0Q5TVDBFZ',
  );
}
